[selection]
fg   = "red"
bold = true

	[selection.prefix]
	prefix = "  "
	size   = 2

[visual_mode_selection]
fg   = "red"
bold = true

[regular]
fg = "white"

[directory]
fg = "light_blue"

[executable]
fg = "green"

[link]
fg = "cyan"

[link_invalid]
fg = "yellow"

[socket]
fg = "magenta"

[ext]
bmp.fg = "light_cyan"

gif.fg = "light_cyan"

heic.fg = "light_cyan"

jpg.fg = "light_cyan"

jpeg.fg = "light_cyan"

pgm.fg = "light_cyan"

png.fg = "light_cyan"

ppm.fg = "light_cyan"

svg.fg = "light_cyan"

wav.fg = "light_yellow"

flac.fg = "light_yellow"

mp3.fg = "light_yellow"

amr.fg = "light_yellow"

avi.fg = "light_yellow"

flv.fg = "light_yellow"

m3u.fg = "light_yellow"

m4a.fg = "light_yellow"

m4v.fg = "light_yellow"

mkv.fg = "light_yellow"

mov.fg = "light_yellow"

mp4.fg = "light_yellow"

mpg.fg = "light_yellow"

rmvb.fg = "light_yellow"

webm.fg = "light_yellow"

wmv.fg = "light_yellow"

7z.fg = "light_magenta"

bz2.fg = "light_magenta"

gz.fg = "light_magenta"

rar.fg = "light_magenta"

tar.fg = "light_magenta"

tgz.fg = "light_magenta"

xz.fg = "light_magenta"

zip.fg = "light_magenta"
